# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 18:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='artist',
            new_name='artist_name',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='founding_date',
        ),
    ]
